from .pyotelem import dives
from .pyotelem import dsp
from .pyotelem import dtag
from .pyotelem import dynamics
from .pyotelem import glides
from .pyotelem import physio_seal
from .pyotelem import plots
from .pyotelem import seawater
from .pyotelem import utils
